# Generated by Django 6.0.3 on 2026-04-04 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emergencyfund_last_contribution_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkIndexDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyFundContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contribution_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(max_length=50)),
                ('scheme_name', models.CharField(max_length=255)),
                ('amc', models.CharField(blank=True, default='', max_length=120)),
                ('category_key', models.CharField(blank=True, default='', max_length=80)),
                ('fund_type', models.CharField(blank=True, default='', max_length=30)),
                ('benchmark_code', models.CharField(blank=True, default='', max_length=50)),
                ('as_of', models.DateField()),
                ('latest_nav', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('return_1y', models.FloatField(default=0)),
                ('return_3y', models.FloatField(default=0)),
                ('return_5y', models.FloatField(default=0)),
                ('volatility_1y', models.FloatField(default=0)),
                ('max_drawdown_1y', models.FloatField(default=0)),
                ('alpha_1y', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('stability_score', models.FloatField(default=0)),
                ('expense_ratio', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundMLSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.IntegerField(db_index=True)),
                ('as_of', models.DateField(db_index=True)),
                ('category_key', models.CharField(db_index=True, max_length=50)),
                ('benchmark_code', models.CharField(db_index=True, max_length=50)),
                ('nav', models.DecimalField(decimal_places=6, max_digits=20)),
                ('ret_1w', models.FloatField(blank=True, null=True)),
                ('ret_1m', models.FloatField(blank=True, null=True)),
                ('vol_1m', models.FloatField(blank=True, null=True)),
                ('bench_ret_1m', models.FloatField(blank=True, null=True)),
                ('alpha_1m', models.FloatField(blank=True, null=True)),
                ('y_fund_ret_1w', models.FloatField(blank=True, null=True)),
                ('y_outperform_1w', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundNavDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('nav', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='FundPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.IntegerField(db_index=True)),
                ('scheme_name', models.CharField(blank=True, default='', max_length=255)),
                ('amc', models.CharField(blank=True, default='', max_length=100)),
                ('category_key', models.CharField(db_index=True, max_length=50)),
                ('benchmark_code', models.CharField(db_index=True, max_length=50)),
                ('as_of', models.DateField(db_index=True)),
                ('pred_for_date', models.DateField(db_index=True)),
                ('pred_nextweek_return', models.FloatField()),
                ('prob_outperform', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundPredictionDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.IntegerField(db_index=True)),
                ('as_of', models.DateField(db_index=True)),
                ('pred_ret_1w', models.FloatField(blank=True, null=True)),
                ('pred_nav_1w', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('prob_outperform_1w', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='xgb_v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(blank=True, default='', max_length=255)),
                ('goal_target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('goal_saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('goal_remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('goal_target_date', models.DateField(blank=True, null=True)),
                ('goal_progress_pct', models.FloatField(default=0)),
                ('goal_priority_score', models.FloatField(default=0)),
                ('scheme_code', models.CharField(max_length=50)),
                ('scheme_name', models.CharField(max_length=255)),
                ('amc', models.CharField(blank=True, default='', max_length=120)),
                ('category_key', models.CharField(blank=True, default='', max_length=80)),
                ('fund_type', models.CharField(blank=True, default='', max_length=30)),
                ('benchmark_code', models.CharField(blank=True, default='', max_length=50)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('suitability', models.CharField(blank=True, default='', max_length=30)),
                ('required_monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('income_based_cap', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('suggested_monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('suggested_horizon_months', models.PositiveIntegerField(default=36)),
                ('summary', models.TextField(blank=True, default='')),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('monthly_income_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_month_expense_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('free_cashflow_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recommendation_pool_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('as_of', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySummaryEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, default='expense', max_length=40)),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('month_key', models.CharField(db_index=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='core_expens_user_id_1376dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='core_expens_user_id_a64772_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_signature',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='direction',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='merchant',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(blank=True, default='UPI', max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('OCR', 'OCR'), ('STATEMENT', 'Statement')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='txn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('ocr_signature__isnull', False)), fields=('user', 'direction', 'source', 'ocr_signature'), name='uniq_expense_ocr_signature_per_user'),
        ),
        migrations.AddField(
            model_name='benchmarkindexdaily',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='core.benchmarkindex'),
        ),
        migrations.AddField(
            model_name='emergencyfundcontribution',
            name='emergency_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.emergencyfund'),
        ),
        migrations.AddField(
            model_name='emergencyfundcontribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_fund_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fundanalyticssnapshot',
            index=models.Index(fields=['category_key', 'as_of'], name='core_fundan_categor_5feecc_idx'),
        ),
        migrations.AddIndex(
            model_name='fundanalyticssnapshot',
            index=models.Index(fields=['fund_type', 'as_of'], name='core_fundan_fund_ty_4c54a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundanalyticssnapshot',
            unique_together={('scheme_code', 'as_of')},
        ),
        migrations.AddIndex(
            model_name='fundmlsample',
            index=models.Index(fields=['benchmark_code', 'as_of'], name='core_fundml_benchma_093c72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundmlsample',
            unique_together={('scheme_code', 'as_of')},
        ),
        migrations.AddIndex(
            model_name='fundnavdaily',
            index=models.Index(fields=['scheme_code', 'date'], name='core_fundna_scheme__2b7499_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundnavdaily',
            unique_together={('scheme_code', 'date')},
        ),
        migrations.AddIndex(
            model_name='fundprediction',
            index=models.Index(fields=['category_key', 'as_of'], name='core_fundpr_categor_786f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='fundprediction',
            index=models.Index(fields=['benchmark_code', 'as_of'], name='core_fundpr_benchma_58cbee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundprediction',
            unique_together={('scheme_code', 'as_of')},
        ),
        migrations.AddIndex(
            model_name='fundpredictiondaily',
            index=models.Index(fields=['as_of'], name='core_fundpr_as_of_2603a6_idx'),
        ),
        migrations.AddIndex(
            model_name='fundpredictiondaily',
            index=models.Index(fields=['scheme_code', 'as_of'], name='core_fundpr_scheme__e71d7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundpredictiondaily',
            unique_together={('scheme_code', 'as_of')},
        ),
        migrations.AddField(
            model_name='investmentrecommendation',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_recommendations', to='core.savingsgoal'),
        ),
        migrations.AddField(
            model_name='investmentrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlysummaryemaillog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='sub_category',
        ),
        migrations.AddIndex(
            model_name='benchmarkindexdaily',
            index=models.Index(fields=['index', 'date'], name='core_benchm_index_i_e229bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='benchmarkindexdaily',
            unique_together={('index', 'date')},
        ),
        migrations.AddIndex(
            model_name='investmentrecommendation',
            index=models.Index(fields=['user', 'as_of'], name='core_invest_user_id_72be03_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentrecommendation',
            index=models.Index(fields=['scheme_code', 'as_of'], name='core_invest_scheme__700f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentrecommendation',
            index=models.Index(fields=['goal', 'as_of'], name='core_invest_goal_id_bc1897_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentrecommendation',
            index=models.Index(fields=['user', 'goal', 'as_of'], name='core_invest_user_id_13ac6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysummaryemaillog',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'month_key'], name='core_recomm_user_id_e91849_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'category'], name='core_recomm_user_id_9bcd14_idx'),
        ),
    ]
